---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.3
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    context: package/
    dockerfile: package/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: cnrancher/fluentd
    tag: ${DRONE_TAG}-linux-amd64
  when:
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote

node:
  instance: agent-amd64
---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    event:
    - tag
trigger:
  event:
    exclude:
    - promote

node:
  instance: agent-amd64

depends_on:
- linux-amd64
